# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_coupon_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ManyToManyField(to='commerce.Coupon'),
        ),
    ]
